# synth: chair, drums, ficus, hotdog, lego, materials, mic, ship
CUDA_VISIBLE_DEVICES=0 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/chair.txt --expname chair --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=1 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/drums.txt --expname drums --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=2 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/ficus.txt --expname ficus --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=3 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/hotdog.txt --expname hotdog --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=4 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/lego.txt --expname lego --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=5 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/materials.txt --expname materials --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=6 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/mic.txt --expname mic --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=7 python run_nerf_ranksched.py --basedir logs_100k/Adam --config configs/ship.txt --expname ship --optimizer ori-adam --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000
wait
# synth: chair, drums, ficus, hotdog, lego, materials, mic, ship
CUDA_VISIBLE_DEVICES=0 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/chair.txt --expname chair --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=1 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/drums.txt --expname drums --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=2 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/ficus.txt --expname ficus --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=3 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/hotdog.txt --expname hotdog --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=4 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/lego.txt --expname lego --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=5 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/materials.txt --expname materials --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=6 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/mic.txt --expname mic --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000&
CUDA_VISIBLE_DEVICES=7 python run_nerf_ranksched.py --basedir logs_100k/Aux-Muon --config configs/ship.txt --expname ship --optimizer aux-muon --train_scheduler original --muon_lrate 3e-3 --lowrank_rank_start 150 --lowrank_rank_end 250 --lowrank_auto_init_rank_start --N_iters 100000
wait